- src/components/Swap.vue
- src/lang/en/index.ts
[PSS-420]: WEB UI. Not have error "Insufficient liquidity for this trade."
1. Add message for insufficient liquidity.
Signed-off-by: Stefan <popov@soramitsu.co.jp>
[PSS-420]: https://soramitsu.atlassian.net/browse/PSS-420
> Add insufficient liquidity message for swap

- src/components/Swap.vue
[PSS-416](https://soramitsu.atlassian.net/browse/PSS-416): WEB UI. Incorrect calculate Minimum received.
1. Added a watcher for `slippageTolerance `to a `Swap.vue`, to recalculate `minMaxRecieved `value after `slippageTolerance `change
Signed-off-by: Nikita-Polyakov<polyakov@soramitsu.co.jp>
[PSS-416]: https://soramitsu.atlassian.net/browse/PSS-416
> PSS-416: add watcher for slippageTolerance in Swap.vue

- src/App.vue
[PSS-470](https://soramitsu.atlassian.net/browse/PSS-470): WEB UI. Unauthorized state. Click on wallet button goes to the account screen.
1. Added a check before navigation to wallet page, that wallet is connected. Otherwise, force wallet navigate to connection view
Signed-off-by: Nikita-Polyakov<polyakov@soramitsu.co.jp>
[PSS-470]: https://soramitsu.atlassian.net/browse/PSS-470
> PSS-470: navigate to wallet connection view on wallet click

- src/components/Swap.vue
[PSS-486](https://soramitsu.atlassian.net/browse/PSS-486): WEB UI. Previous data is memorable in input field.
[PSS-486]: https://soramitsu.atlassian.net/browse/PSS-486
> PSS-486: reset swap values in vuex after transaction

- src/components/SelectToken.vue
- src/components/Swap.vue
[PSS-351](https://soramitsu.atlassian.net/browse/PSS-351): WEB UI. Select token. Token balance is not displayed.
1. Refactored an `assetsList ` computed property to return an array of objects `AccountAsset ` type, that have a `balance `property
[PSS-351]: https://soramitsu.atlassian.net/browse/PSS-351
> PSS-351: Show balance in select token dialog

- src/components/SelectToken.vue
- src/views/AddLiquidity.vue
- src/views/CreatePair.vue
[PSS-351]: WEB UI. Select token. Token balance is not displayed.
1. Show "0" balance as "-" (following design)
2. Pass `connected ` props to all SelectToken components
[PSS-351]: https://soramitsu.atlassian.net/browse/PSS-351
> PSS-351 Select Token fixes

- src/components/PageNotFound.vue
- src/components/Pool.vue
- src/consts/index.ts
- src/lang/en/index.ts
- src/router/index.ts
- src/styles/_mixins.scss
- src/utils/index.ts
- src/views/AddLiquidity.vue
- src/views/RemoveLiquidity.vue
[PSS-516]: WEB UI. Can go to remove liquidity page without liquidity on account.
1. Added Page Not Found Draft.
2. Fixed Add and Remove Liquidity router bags.
3. Hid some screens for unauthorized access.
4. Added redirect to exchange for Page Not Found error.
5. Disabled selects for existed liquidity addition.
[PSS-516]: https://soramitsu.atlassian.net/browse/PSS-516
> PSS-516: WEB UI. Can go to remove liquidity page without liquidity on account

- src/components/SelectToken.vue
- src/components/mixins/TokenPairMixin.ts
- src/views/Swap.vue
https://soramitsu.atlassian.net/browse/PSS-568
> remove getAssets from select-token dialog

- src/lang/en/index.ts
- src/views/BridgeTransactionsHistory.vue
[PSS-590]: Add history to the account tab
Added Account History.
[PSS-590]: https://soramitsu.atlassian.net/browse/PSS-590
> PSS-590: Add History to the Account tab

- package.json
- src/components/ConfirmBridgeTransactionDialog.vue
- src/components/ConfirmSwap.vue
- yarn.lock
[PSS-675]: Web UI: Send. Token symbol slides out of the border in case of large precision
* Bridge: Formatted amounts for Confirm dialog.
[PSS-675]: https://soramitsu.atlassian.net/browse/PSS-675
> PSS-675: Web UI: Send. Token symbol slides out of the border in case of large precision

- package.json
- vue.config.js
- yarn.lock
[PSS-587]: WEB UI. Sometimes elements on page can be broken..
Sass processor transform unicode chars to utf-8 chars, so in css files we could see icon content a strange symbols. When browser loads css file from cache, sometimes it's uncorrectly parses this icon content (and render this icons using Times New Roman, not soramitsu-icons)
It looks like the correct way is to deliver css files with unicode content as real unicode, as the font-awesome library does
[PSS-587]: https://soramitsu.atlassian.net/browse/PSS-587
> PSS-587: Fix icon font content using css-unicode-loader

- package.json
- src/App.vue
- src/components/SwapInfo.vue
- src/components/mixins/TokenPairMixin.ts
- src/components/mixins/WalletConnectMixin.ts
- src/router/index.ts
- src/store/pool.ts
- src/utils/index.ts
- src/views/AddLiquidity.vue
- src/views/CreatePair.vue
- src/views/Pool.vue
- src/views/RemoveLiquidity.vue
- src/views/Rewards.vue
- src/views/Swap.vue
- yarn.lock
[PSS-737]: WEB UI. Re-login incorrect wallet state.
1. Updated wallet to 0.9.9
2. Refactoring components to use `isLoggedIn` getter from wallet, to have a correct reactive view updates
Signed-off-by: Nikita-Polyakov <polyakov@gmail.com>
[PSS-737]: https://soramitsu.atlassian.net/browse/PSS-737
> PSS-737: Update wallet to sync account state between tabs

- src/utils/web3-util.ts
I found that every call `new Web3(provider)` adds the same event listeners to ` window.ethereum`, and this causes the warnings for possible memory leaks of `EventEmitter`
Also added a change, that `watchEthereum` util function return a callback, that removes event listeners added only from our side
Event listeners before changes
Event listeners after changes
> Use web3Instance as singletone

- src/components/mixins/WalletConnectMixin.ts
- src/views/Bridge.vue
- src/views/Rewards.vue
When user goes to `Bridge `or `Rewards `page, we should check a current external account address - because user could change account using Meatamask extension on another page
> add syncExternalAccountWithAppState method

- src/store/addLiquidity.ts
- src/store/swap.ts
- src/utils/index.ts
- src/views/Swap.vue
[PSS-801]: WEB UI: Max button isn't shown in SWAP until some amount entered.
1. Updated `isMaxButtonAvailable` & related util functions
2. Reset Swap page during `created ` hook
3. Add liquidity - reset opposite field, if focused field is clear
[PSS-801]: https://soramitsu.atlassian.net/browse/PSS-801
> PSS-801: Show max button if fee is like zero value

- src/views/BridgeTransaction.vue
[PSS-881]: WEB UI. Bridge. No message on Retry button if the balance is not enough.
* Bridge Transaction: Fixed Retry Button Message for Insufficient Balance.
[PSS-881]: https://soramitsu.atlassian.net/browse/PSS-881
> PSS-881: Bridge Transaction - Retry Button Message for Insufficient Balance

- src/views/Rewards.vue
[PW-355]: Wrong $ amount at strategic rewards for PSWAP
* Rewards: Fixed fiat value error.
[PW-355]: https://soramitsu.atlassian.net/browse/PW-355
> PW-355: Wrong $ amount at strategic rewards for PSWAP

- src/components/ConfirmRemoveLiquidity.vue
- src/store/addLiquidity.ts
- src/store/removeLiquidity.ts
- src/views/RemoveLiquidity.vue
[PW-330]: Remove liquidity pool subscription
> Remove liquidity: reactive updates

- Jenkinsfile
Signed-off-by: Ahmed Elkashef <elkashef@soramitsu.co.jp>
Use the extended ubuntu-14 Docker Image.
1. Use the extended ubuntu-14 Docker Image.
> Use extended ubuntu 14 dockerImage

- src/components/TransactionDetails/SwapTransactionDetails.vue
- src/lang/cs.json
- src/lang/de.json
- src/lang/en.json
- src/lang/es.json
- src/lang/fr.json
- src/lang/hy.json
- src/lang/id.json
- src/lang/it.json
- src/lang/messages.ts
- src/lang/nl.json
- src/lang/no.json
- src/lang/pl.json
- src/lang/ru.json
- src/lang/yo.json
- src/views/BridgeTransaction.vue
[PW-639]: Bridge. Text: Please wait 30 blocks is redundant
> Bridge: remove redundant message, fix confirmation message for evm part

- package.json
- vue.config.js
- yarn.lock
This commit will remove data-test attributes specified in vue.config.js -> testAttrs array -> ['test', 'testid', 'test-name'], meaning, these combinations:
1) `data-test="..."`
2) `data-testid="..."`
3) `data-test-name="..."`
for production (yarn build) and local development (yarn serve)
> add plugin & adjust config

- src/components/Moonpay/MoonpayBridgeInitMixin.ts
- src/components/mixins/SubscriptionsMixin.ts
- src/components/mixins/WalletConnectMixin.ts
- src/views/BridgeContainer.vue
- src/views/Rewards.vue
[PW-709]: The user cannot see the page data until he logs into Metamask
> [PW-709] Remove initial sync with metamask on page loading

- package.json
- src/router/index.ts
- yarn.lock
[vue-router] Named Route 'PoolContainer' has a default child route. When navigating to this named route (:to="{name: 'PoolContainer'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
1. Fix router warning.
> Fix router warning

- env.json
- package.json
- src/components/SelectAsset/SelectToken.vue
- src/components/Settings/MarketAlgorithm.vue
- src/components/Settings/SlippageTolerance.vue
- src/components/Swap/Chart.vue
- src/modules/demeterFarming/components/CalculatorDialog.vue
- src/modules/demeterFarming/components/ClaimDialog.vue
- src/modules/demeterFarming/components/StakeDialog.vue
- src/modules/demeterFarming/mixins/StakeDialogMixin.ts
- src/modules/demeterFarming/views/Pool.vue
- src/modules/demeterFarming/views/Staking.vue
- src/views/AddLiquidity.vue
- src/views/ReferralProgram.vue
- src/views/RemoveLiquidity.vue
- src/views/RewardsTabs.vue
- yarn.lock
https://soramitsu.atlassian.net/browse/PW-980
> Fix confirm buttons loading state

- package.json
- src/store/bridge/actions.ts
- src/store/swap/mutations.ts
- src/utils/bridge/eth/classes/history.ts
- src/views/Swap.vue
- yarn.lock
https://soramitsu.atlassian.net/browse/PW-1256
> Fix subquery bridge history

- src/consts/snapshots.ts
- src/types/filters.ts
[PW-1415]: Add 6M filter for stats page
1. Add 6M filter for stats page.
[PW-1415]: https://soramitsu.atlassian.net/browse/PW-1415
> Add 6M filter for stats page

- src/store/bridge/actions.ts
- src/utils/bridge/sub/classes/history.ts
- src/utils/bridge/sub/utils.ts
- src/views/BridgeTransaction.vue
https://soramitsu.atlassian.net/browse/PW-1615
https://soramitsu.atlassian.net/browse/PW-1616
> [Bridge] fix issues

- src/components/App/Menu/AppMenu.vue
[PW-1614]: Mobile menu is overlapped by page content while page is loading.
[PW-1614]: https://soramitsu.atlassian.net/browse/PW-1614
> z-index updated

- src/components/shared/Settings/SlippageTolerance.vue
Minor bug: dot did't changed for comma when change language
> fixed incorrect delimiter, when user change language

- src/components/App/Alerts/AlertList.vue
- src/components/App/Alerts/CreateAlert.vue
- src/components/App/Settings/Node/NodeInfo.vue
- src/components/App/Settings/Node/SelectNode.vue
- _Removed dirty hack for dialog re-center because the base dialog component was already improved so there is no need for that hack anymore_
- _To remove doubled source code_
---
---
- [Related PW-1749 issue](https://soramitsu.atlassian.net/browse/PW-1749)
---
- _Check it using any of modal dialog with dynamic content_
> Remove dirty hack for dialog re-center

- src/components/pages/OrderBook/TransactionDetails.vue
- _I've fixed base & quote symbols for TX Details in Orderbook_
- _To show correct info in Orderbook TX Details Widget_
---
---
- _[Issue](https://soramitsu.atlassian.net/browse/PW-1795)_
---
- _Verify the correct symbols from the screenshot below_
---
---
> Fix base & quote symbols for TX Details in Orderbook

- package.json
- src/components/App/Menu/AppMenu.vue
- src/components/shared/Widget/Grid.vue
- src/lang/cs.json
- src/lang/de.json
- src/lang/en.json
- src/lang/es.json
- src/lang/fr.json
- src/lang/id.json
- src/lang/it.json
- src/lang/nl.json
- src/lang/pl.json
- src/lang/ru.json
- src/lang/sr.json
- src/lang/vi.json
- src/lang/zh_CN.json
- yarn.lock
- _I've migrated Kensetsu math from ms to seconds to make the math backward compatible with the blockchain_
- _Also, I've added start unlocking date for the vested transfers_
- _And fixed some a11y issues_
- _Backward compatibility for the Kensetsu math_
- _Better UX_
---
---
- _[Add new stability fee support](https://soramitsu.atlassian.net/browse/PW-1635)_ 
- _[As a user I'd like to select start unlocking date](https://soramitsu.atlassian.net/browse/PW-1812)_
---
- _Check Kensetsu math related to the stability fee and bad debt calculation; ensure that everything is correct and works the same with the blockchain
- _Play with start unlocking date of vested transfers; ensure it works as expected_ …
> Kensetsu migration to seconds, vested transfer upgrade, a11y improvements
