package.json, public/env.json, src/App.vue, src/components/ConfirmSwap.vue, src/components/Swap.vue, src/components/mixins/TransactionMixin.ts, src/store/addLiquidity.ts, src/store/assets.ts, src/store/createPair.ts, src/store/pool.ts, src/store/prices.ts, src/store/removeLiquidity.ts, src/store/swap.ts, yarn.lock
[PSS-421](https://soramitsu.atlassian.net/browse/PSS-421): WEB UI. Can't go to wallet through click on wallet icon from transfer page.
1. Updated `sora2-wallet-web` version to `0.4.7`
2. Constant `RouteNames` is imported from `sora2-wallet-web` to `App.vue`
3. Changed a `goTo` method to check, should we show a default wallet view when app's handling navigation to wallets page
[PSS-421]: https://soramitsu.atlassian.net/browse/PSS-421
=> PSS-421: WEB UI. Can't go to wallet through click on wallet icon from transfer page.

src/components/SwapInfo.vue
[PSS-400]: WEB UI. Minimum receive/Maximum sold token not changed.
Fixed min received/max sold symbol.
[PSS-400]: https://soramitsu.atlassian.net/browse/PSS-400
=> PSS-400: WEB UI. Minimum receive/Maximum sold token not changed

package.json, src/App.vue, src/store/swap.ts, yarn.lock
[PSS-467]: On the swap screen user should be able to select all tokens except pool tokens.
1. Fix swap operation with assets created by users.
Signed-off-by: Stefan Popov <popov@soramitsu.co.jp>
[PSS-467]: https://soramitsu.atlassian.net/browse/PSS-467
=> PSS-467: On the swap screen user should be able to select all tokens excecpt pool tokens

package.json, src/components/mixins/TransactionMixin.ts, yarn.lock
[PSS-396](https://soramitsu.atlassian.net/browse/PSS-396): WEB UI. Cannot read property 'id' of null.
1. Added little fixes in wallet
[PSS-396]: https://soramitsu.atlassian.net/browse/PSS-396
=> PSS-396: apply transaction mixin changes from wallet

package.json, src/components/Settings.vue, src/components/Swap.vue, src/components/mixins/TokenPairMixin.ts, src/utils/index.ts, src/views/AddLiquidity.vue, yarn.lock
SFloatInput fixes
Reseted values and tokens for Add Liquidity and Create Pair components, added placeholders for all SFloatInput elements.
=> SFloatInput Fixes

src/components/SelectToken.vue, src/components/Swap.vue
=> Hotfix: fix 'openSelectTokenDialog' method

src/components/SelectToken.vue
=> Change s-form-item to div in SelectToken dialog

package.json, src/components/Settings.vue, src/components/Swap.vue, src/lang/en/index.ts, src/store/settings.ts, yarn.lock
[PSS-248]: Web UI: Settings - Problems with input in Custom field
1. `slippageTolerance ` default value is setted after blur, to allow user delete all value symbols
2.  Added % symbol after value as in [design](https://www.figma.com/file/npcxk5W14KSn4A4yaj9riE/Polkaswap-web-(current)?node-id=5676%3A4)
[PSS-248]: https://soramitsu.atlassian.net/browse/PSS-248
=> PSS-248 Web UI: Settings - Problems with input in Custom field

LICENSE, package.json, src/App.vue, src/components/ConfirmRemoveLiquidity.vue, src/components/ConfirmSwap.vue, src/components/ConfirmTokenPairDialog.vue, src/components/PairTokenLogo.vue, src/components/Pool.vue, src/components/ResultDialog.vue, src/components/SelectToken.vue, src/components/Settings.vue, src/components/Swap.vue, src/components/SwapInfo.vue, src/components/TokenLogo.vue, src/components/mixins/NumberFormatterMixin.ts, src/components/mixins/TokenPairMixin.ts, src/consts/index.ts, src/store/addLiquidity.ts, src/store/createPair.ts, src/store/prices.ts, src/store/removeLiquidity.ts, src/store/swap.ts, src/types/index.ts, src/utils/index.ts, src/views/AddLiquidity.vue, src/views/CreatePair.vue, src/views/RemoveLiquidity.vue, yarn.lock
[PSS-418]: Precision management.
1. Improve all number values in project.
2. Update toto sections.
3. Fix some issues.
Signed-off-by: Stefan Popov <name@soramitsu.co.jp>
[PSS-418]: https://soramitsu.atlassian.net/browse/PSS-418
=> PSS-418: Precision management

package.json, yarn.lock
[PSS-294]: WEB UI: Restrict Send if balance is insufficient
[PSS-294]: https://soramitsu.atlassian.net/browse/PSS-294
=> PSS-294: Update wallet

package.json, yarn.lock
Updated wallet version to 0.6.3
=> Wallet version 0.6.3

package.json, yarn.lock
* Updated wallet version to 0.6.4.
=> Wallet Version Update 0.6.4

src/components/BrandedTooltip.vue, src/components/ConfirmRemoveLiquidity.vue, src/components/ConfirmTokenPairDialog.vue, src/components/GenericPageHeader.vue, src/components/InfoLine.vue, src/components/SwapInfo.vue, src/lang/en/index.ts, src/styles/_layout.scss, src/styles/_mixins.scss, src/views/About.vue, src/views/AddLiquidity.vue, src/views/Bridge.vue, src/views/CreatePair.vue, src/views/Pool.vue, src/views/RemoveLiquidity.vue, src/views/Swap.vue
1. Refactored buttons styles, changed some translation to common one.
2. Updated tooltips, screens info area.
3. Updated info blocks.
=> Redesign Updates

package.json, src/consts/index.ts, src/store/bridge.ts, src/views/Bridge.vue, yarn.lock
[PSS-573]: WEB UI. MAX button for bridge work incorrect.
[PSS-573]: https://soramitsu.atlassian.net/browse/PSS-573
=> PSS-573 WEB UI. MAX button for bridge work incorrect.

src/lang/en/index.ts
Fixed type on 'Conversion' word
=> Fixed type on 'Conversion' word

package.json, src/lang/en/index.ts, yarn.lock
=> Sora Renaming

package.json, src/App.vue, vue.config.js, yarn.lock
[PSS-527]: Generate account icon for account.
1. Added icon generation component
[PSS-527]: https://soramitsu.atlassian.net/browse/PSS-527
=> PSS-527: Import icon generation component from wallet

package.json, src/consts/index.ts
[PSS-596]: WEB UI. Change media links.
1. Update social links.
[PSS-596]: https://soramitsu.atlassian.net/browse/PSS-596
=> PSS-596 | WEB UI. Change media links

package.json, src/components/Settings.vue, src/components/mixins/NumberFormatterMixin.ts, src/views/AddLiquidity.vue, src/views/Bridge.vue, src/views/CreatePair.vue, src/views/RemoveLiquidity.vue, src/views/Swap.vue, yarn.lock
[PSS-399]: WEB UI. Not have boundary for input field.
[PSS-454]: WEB UI. Add liquidity. Not have input boundary.
1. Add boundary for input fields.
Signed-off-by: Stefan Popov <popov@soramitsu.co.jp>
[PSS-399]: https://soramitsu.atlassian.net/browse/PSS-399
[PSS-454]: https://soramitsu.atlassian.net/browse/PSS-454
=> Add token boundaries

src/components/Settings.vue
[PSS-595]: WEB UI. The slippage tolerance should be limited 
[PSS-248]: Web UI: Settings - Problems with input in Custom field 
1. Improved field handling
Signed-off-by: Robert Sayakhov <sayakhov@soramitsu.co.jp>
[PSS-595]: https://soramitsu.atlassian.net/browse/PSS-595
[PSS-248]: https://soramitsu.atlassian.net/browse/PSS-248
=> Web UI: Settings - Problems with input in Custom field 

src/components/ConfirmBridgeTransactionDialog.vue, src/components/SelectRegisteredAsset.vue, src/lang/en/index.ts, src/styles/_mixins.scss, src/views/Bridge.vue, src/views/BridgeTransactionsHistory.vue
Updated some layout behaviour.
=> Layout Updates

src/components/AboutNetworkDialog.vue, src/components/DialogBase.vue, src/consts/index.ts, src/lang/en/index.ts, src/views/Wallet.vue
[PSS-658]: WEB UI. Add "About" modal
1. Added AboutNetworkDialog component
2. Placed in inside Wallet View
[PSS-658]: https://soramitsu.atlassian.net/browse/PSS-658
=> Add "About" modal

package.json, src/store/assets.ts, yarn.lock
Updated wallet version to 0.8.3.
=> Wallet Version Update 0.8.3

src/components/SelectRegisteredAsset.vue, src/store/assets.ts, src/store/web3.ts, src/utils/index.ts, src/views/Bridge.vue
[PSS-588]: WEB UI. Balance for ETH token may be shown as NaN
1. Refactoring `SelectRegisteredAsset `component
2. Refactoring `assets/updateRegisteredAssets` store action
[PSS-588]: https://soramitsu.atlassian.net/browse/PSS-588
=> PSS-588: fetch & update registered assets by the one flow

src/lang/en/index.ts, src/views/Bridge.vue
[PSS-536]: WEB UI. Bridge. Change message on a button when token is not chosen.
1. Added a message "Choose a token" to the bridge button
[PSS-536]: https://soramitsu.atlassian.net/browse/PSS-536
=> PSS-536: Add  "Choose a token" button message

package.json, src/components/SelectRegisteredAsset.vue, src/components/SelectToken.vue, src/components/Settings/MarketAlgorithm.vue, src/components/Settings/Tabs.vue, src/components/SettingsDialog.vue, src/components/mixins/TokenPairMixin.ts, src/consts/index.ts, src/store/assets.ts, src/store/settings.ts, src/store/swap.ts, src/types/tabs.ts, src/utils/index.ts, src/views/Bridge.vue, src/views/RemoveLiquidity.vue, src/views/Swap.vue, yarn.lock
1. Added fetching `liquiditySources` for swap after the user changes a pair of tokens
2. Refactored balances formatting (according to wallet update), added some utility functions for reusing them in code
=> PSS-628: Fetch liquidity sources for swap pair

src/lang/en/index.ts, src/store/swap.ts, src/views/Swap.vue
[PSS-574]: WEB UI. Not have error about "Pair is not registered"
* Swap: Added pair is not created check.
[PSS-574]: https://soramitsu.atlassian.net/browse/PSS-574
=> PSS-574: WEB UI. Not have error about "Pair is not registered"

src/App.vue, src/components/Settings/SlippageTolerance.vue, src/views/Bridge.vue, src/views/BridgeTransaction.vue
Fixed:
1) Strange states wallet button
2) Fee tooltip texts on bridge, unsifficient balance message argument
3) Hide percent on focus slippage tolerance custom field
=> fix translations, wallet button, slippage tolerance focus

package.json, yarn.lock
* Updated wallet version to 0.9.0.
=> Wallet Version Update 0.9.0

src/components/SelectRegisteredAsset.vue, src/components/SelectToken.vue
[PSS-729]: WEB UI. Bridge. Select a token. Token icon shrinks if you have a large balance.
Fixed Select token layout.
[PSS-729]: https://soramitsu.atlassian.net/browse/PSS-729
=> PSS-729: WEB UI. Bridge. Select a token. Token icon shrinks if you have a large balance.

src/utils/index.ts, src/views/Bridge.vue, src/views/BridgeTransaction.vue
[PSS-728]: Title.
1. If asset is not registered, show related message first, not "enter amount"
2. Improve insufficient balance check on bridge
[PSS-728]: https://soramitsu.atlassian.net/browse/PSS-728
=> PSS-728: fix messages & insufficient balance check

src/App.vue, src/components/ConfirmBridgeTransactionDialog.vue, src/components/ConfirmSwap.vue, src/components/SwapInfo.vue, src/lang/en/index.ts, src/views/AddLiquidity.vue
* Fixed some layout, translation, tooltip issues.
=> Layout, Translation, Tooltip Improvements

src/components/SelectToken.vue, src/lang/en/index.ts
[PSS-736]: WEB UI. Add token on swap page, search by token name work incorrectly.
=> PSS-736: SelectToken - add filtering by name

src/store/bridge.ts, src/store/web3.ts, src/utils/fsm.ts, src/views/BridgeTransaction.vue
[PSS-578]: WEB UI. Bridge. Pending transaction - multiple sign request.
1. Major update of state machine
2. History functionality removed from vuex and now performs in FSM
3. Other improvements of sign and send function for SORA and ETH
Signed-off-by: Robert Sayakhov <sayakhov@soramitsu.co.jp>
[PSS-578]: https://soramitsu.atlassian.net/browse/PSS-578
=> PSS-578 | State machine update

src/App.vue, src/lang/en/index.ts, src/styles/_mixins.scss
[PSS-750]: Web UI. Add disclaimer to every page
Added disclaimer to all pages.
[PSS-750]: https://soramitsu.atlassian.net/browse/PSS-750
=> PSS-750: Web UI. Add disclaimer to every page

src/lang/en/index.ts
Fixes msg that is too long
Signed-off-by: Makoto Takemiya t@soramitsu.co.jp
=> minor msg update

src/App.vue, src/components/SidebarItemContent.vue, src/lang/en/index.ts
[PSS-751]: Web UI. Update links to privacy policy and terms of service
Added Terms of Service and Privacy Policy links.
[PSS-751]: https://soramitsu.atlassian.net/browse/PSS-751
=> PSS-751: Web UI. Update links to privacy policy and terms of service

public/env.json, src/App.vue, src/lang/en/index.ts, src/store/web3.ts, src/utils/web3-util.ts
[PSS-772]: Add network configuration.
Added Sub Networks configuration.
[PSS-772]: https://soramitsu.atlassian.net/browse/PSS-772
=> PSS-772: Add Network Configuration

package.json, src/components/SwapInfo.vue, src/lang/en/index.ts, src/store/swap.ts, src/views/Swap.vue, yarn.lock
[PSS-755]: WEB UI. Display the reward on the swap screen.
1. Changed api method for fetching liquidity sources from `getEnabledLiquiditySourcesForPair` to `getListEnabledSourcesForPath`
2. Added rewards to `SwapInfo` component
=> WEB UI. Display the reward on the swap screen

src/utils/index.ts, src/views/Swap.vue
[PSS-812] WEB UI: Update logic for swapping without owning XOR
Swap screen: Added swap to XOR with lack of XOR for fee.
[PSS-812]: https://soramitsu.atlassian.net/browse/PSS-812
=> PSS-812: WEB UI: Update logic for swapping without owning XOR

src/components/ConfirmBridgeTransactionDialog.vue, src/store/bridge.ts, src/store/web3.ts, src/utils/index.ts, src/views/Bridge.vue, src/views/BridgeTransaction.vue, src/views/BridgeTransactionsHistory.vue
[PSS-788]: WEB UI. Incorrect Balance query for ETH token.
1. Added an utility function, `isEthereumAddress` to handle registered ethereum asset correctly
2. Store `ethBalance`, `ethereumNetworkFee `as `CodecString`
3. Improved bridge max button checks and `getMaxBalance` utility function
[PSS-788]: https://soramitsu.atlassian.net/browse/PSS-788
=> PSS-788: WEB UI. Incorrect Balance query for ETH token

src/lang/en/index.ts, src/views/BridgeTransaction.vue
Simple change to add info about having to wait 30 blocks to the user, as people ask this question about 100 times a day.
Signed-off-by: Makoto Takemiya <t@soramitsu.co.jp>
=> add text msg

src/lang/en/index.ts
[PSS-865]: Fix typo AWARDS to REWARDS.
[PSS-865]: https://soramitsu.atlassian.net/browse/PSS-865
=> Fix typo Awards -> Rewards

src/store/rewards.ts
=> Removed console.info

src/views/About.vue
Signed-off-by: name <name@gmail.com>
=> changed youtube video link

src/components/mixins/WalletConnectMixin.ts, src/lang/en/index.ts, src/utils/web3-util.ts
[PSS-894]: WEB UI. Connect MetaMask. Error about additional request appear with not clear message.
=> PSS-894: Improve bridge alert messages

src/store/rewards.ts, src/views/Rewards.vue
[PSS-889]: WEB UI. Rewards. Claim button available before getting the network fee
=> PSS-889: Disable claim button when fee is fetching

src/components/ConfirmBridgeTransactionDialog.vue, src/components/SelectRegisteredAsset.vue, src/lang/en/index.ts, src/styles/overrides.scss, src/utils/index.ts, src/views/Bridge.vue, src/views/BridgeTransaction.vue, src/views/BridgeTransactionsHistory.vue
* Removed token prefixes.
* Added networks icons.
=> Bridge: Network Icons, Assets Prefixes Removing

src/components/SelectToken.vue, src/lang/en/index.ts
=> Search Placeholder Update

src/components/SelectRegisteredAsset.vue, src/lang/en/index.ts, src/views/BridgeTransaction.vue, src/views/BridgeTransactionsHistory.vue
1. Bridge Select Asset: Removed Mirror Prefix.
2. Bridge Transactions: Fixed Amount Format.
=> Removing Mirror Labels

src/components/StatusActionBadge.vue
Signed-off-by: name <name@gmail.com>
=> fix padding alignment StatusActionBadge

package.json, src/components/SelectRegisteredAsset.vue, src/components/SelectToken.vue, src/components/mixins/TransactionMixin.ts, yarn.lock
[PSS-822]: WEB UI. The activity list is cleared after re-login
[PSS-884]: WEB UI. UX improve. After click "Choose token" focus should be switch to "Find field"
[PSS-822]: https://soramitsu.atlassian.net/browse/PSS-822
[PSS-884]: https://soramitsu.atlassian.net/browse/PSS-884
=> Move history to account storage

package.json, src/App.vue, src/components/ConfirmBridgeTransactionDialog.vue, src/lang/en/index.ts, src/store/bridge.ts, src/styles/overrides.scss, src/views/BridgeTransaction.vue, src/views/BridgeTransactionsHistory.vue, yarn.lock
[PSS-900]: Read history for bridge transactions from RPC
[PSS-902]: Get transaction details from RPC api by hash
[PSS-903]: Save transaction in history
1. Bridge History: Added Restore History Button, Set Restored Flag, Get Account Requests and Requests info.
2. Bridge Restored History: Filled history on Restore Button click.
3. Bridge Restored History: Added comments.
[PSS-900]: https://soramitsu.atlassian.net/browse/PSS-900
[PSS-902]: https://soramitsu.atlassian.net/browse/PSS-902
[PSS-903]: https://soramitsu.atlassian.net/browse/PSS-903
=> PSS-900: Restore Bridge History

package.json, src/components/SelectToken.vue, src/store/assets.ts, src/views/Swap.vue, yarn.lock
[PSS-821]: WEB UI. The list of account tokens is cleared after re-loggin.
[PSS-821]: https://soramitsu.atlassian.net/browse/PSS-821
=> Update account assets storage

src/components/SelectNodeDialog.vue, src/store/settings.ts
[PSS-972]: WEB UI. Node selection. When you change nodes, the connection to the old not turn off
[PSS-972]: https://soramitsu.atlassian.net/browse/PSS-972
=> PSS-972: node connection fixes

package.json, src/components/Rewards/AmountTable.vue, src/store/rewards.ts, src/views/Rewards.vue, yarn.lock
[PSS-1007]: WEB UI. Rewards. The page loads jerkily
[PSS-1007]: https://soramitsu.atlassian.net/browse/PSS-1007
=> Rewards Checkboxes

package.json, src/components/mixins/TokenPairMixin.ts, src/store/addLiquidity.ts, src/store/bridge.ts, src/store/createPair.ts, src/store/swap.ts, src/utils/subscriptions.ts, src/views/Bridge.vue, yarn.lock
Add balance subscription to the bridge
[PSS-989]: Subscribe to token balance when it's selected by user
[PSS-990]: Unsubscribe from the token balance when user selects another token
[PSS-989]: https://soramitsu.atlassian.net/browse/PSS-989
[PSS-990]: https://soramitsu.atlassian.net/browse/PSS-990
=> Add balance subscription to the bridge

src/store/bridge.ts, src/views/Bridge.vue
[PSS-1020]: WEB UI. Bridge ETH <-> SORA transfers is broken.
[PSS-1020]: https://soramitsu.atlassian.net/browse/PSS-1020
=> Reset bridge subscription instead of form

src/lang/en/index.ts, src/views/Rewards.vue
[PSS-1014]: Update rewards texts
[PSS-1014]: https://soramitsu.atlassian.net/browse/PSS-1014
=> Change rewards table text

src/components/SelectRegisteredAsset.vue, src/components/SelectToken.vue, src/components/mixins/SelectAssetMixin.ts
[PSS-1018]: WEB UI. Bridge. SORA->ETH the select token shows only added tokens.
[PSS-1018]: https://soramitsu.atlassian.net/browse/PSS-1018
=> Show whitelist tokens in bridge

package.json, src/App.vue, src/components/SelectNodeDialog.vue, src/components/mixins/NodeErrorMixin.ts, src/store/settings.ts, src/types/nodes.ts, src/views/Swap.vue, yarn.lock
[PSS-1013]: WEB UI. Double runtime request.
[PSS-971]: WEB UI. Node selection. If the connection is broken - endless processing.
[PSS-1013]: https://soramitsu.atlassian.net/browse/PSS-1013
[PSS-971]: https://soramitsu.atlassian.net/browse/PSS-971
=> Node connection improvements

package.json, src/components/SelectNodeDialog.vue, src/components/mixins/DialogMixin.ts, src/components/mixins/NodeErrorMixin.ts, src/store/settings.ts, yarn.lock
[PW-113]: WEB UI. Select node. Can't reconnect to if delete current account.
[PW-113]: https://soramitsu.atlassian.net/browse/PW-113
=> Fix wallet init breaking, handle connection close error

src/components/ConfirmBridgeTransactionDialog.vue, src/store/bridge.ts, src/store/web3.ts, src/views/BridgeTransaction.vue
Fixed several bugs related to the bridge.
=> fix: abi of undefined contract

src/components/Settings/Node/NodeInfo.vue, src/utils/regexp.ts
[PW-399]: Can't add the node with the path in the URL
=> Improve regexp for dns: allow path

src/utils/regexp.ts
[PW-399]: Can't add the node with the path in the URL
Fixed:
`Please add opportunity for connect to ip/path addresses like a wss://192.168.0.1:9876/sora-dev`
=> Add segment to ip regexp

package.json, src/App.vue, src/store/settings.ts, yarn.lock
[PW-431](https://soramitsu.atlassian.net/browse/PW-431?atlOrigin=eyJpIjoiMzZhZjg5NGNmZDkwNDZlNzg3ZjI5NDdmZGI5ZDdhZjciLCJwIjoiaiJ9)
=> Add block number

.github/pull_request_template.md
=> PR Template Update

package.json, tests/mocks/account.ts, tests/unit/components/App/Header/AccountButton.spec.ts, tests/unit/components/App/Header/__snapshots__/AccountButton.spec.ts.snap, tests/unit/components/__snapshots__/SwapInfo.spec.ts.snap, tests/utils/index.ts, yarn.lock
This PR adds translations into components snapshots
=> add account button unit-test

package.json, src/App.vue, src/components/App/Header/AppHeader.vue, src/components/App/Menu/AppMenu.vue, src/store/swap.ts, src/views/Swap.vue, yarn.lock
[PW-500]: Make the Market algorithm button is unavailable for single market
[PW-505]: Allow to use TBC market algorythm for enabled collateral assets
=> [1.6.0] Fix swap issues

src/components/ExternalLink.vue, src/components/HelpDialog.vue, src/views/Swap.vue
[PW-506]: Swap button has text "swap" with disabled state
=> Fix "swap" button

src/utils/index.ts
=> Release 1.6.1

package.json, yarn.lock
* Update wallet version (#559)
* Release 1.6.1 (#560)
* Downgrade wallet version
* Fix ETH decimals
* Fix external decimals for bridge (#563)
* Add 1.3 back-end support (#567)
* Add 1.3 back-end support (#567)
* Fix swap related issues (#574)
=> Fleek: Release 1.6.2

src/components/mixins/TokenPairMixin.ts, src/views/AddLiquidity.vue
[PW-556]: Add liquidity screen. Prices is broken at the Transaction details
=> Fix AddLiquidity updatePrice params

package.json, src/components/SelectToken.vue, yarn.lock
[PW-529]: Improve history performance
https://soramitsu.atlassian.net/browse/PW-529
=> Improve history performance

package.json, src/views/ReferralProgram.vue, yarn.lock
=> Referral Rewards Fix

package.json, src/App.vue, src/views/BridgeTransaction.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-605
=> Show expected address message when eth part not signed

package.json, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/yo.json, src/plugins/wallet.ts, src/styles/soramitsu-variables.scss, yarn.lock
QR code support
https://soramitsu.atlassian.net/browse/PW-403
Virtual scroll in assets list (wallet)
https://soramitsu.atlassian.net/browse/PW-493
User sees wrong amount when he made batch transaction (Create pair)
https://soramitsu.atlassian.net/browse/PW-610
Claiming Rewards transaction disappears from history when transaction is failed
https://soramitsu.atlassian.net/browse/PW-610
=> QR code support

src/components/ConfirmBridgeTransactionDialog.vue, src/components/Rewards/AmountTable.vue, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/messages.ts, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/yo.json, src/plugins/soramitsuUI.ts, src/store/rewards.ts, src/types/rewards.ts, src/views/Rewards.vue
[PW-594]: Add crowdload rewards
=> Crowdloan rewards

src/views/ReferralProgram.vue
[PW-599]: Add pagination for referrals list.
1. Referrals list: Added pagination.
[PW-599]: https://soramitsu.atlassian.net/browse/PW-599
=> PW-599: Add pagination for referrals list

package.json, src/store/pool/actions.ts, src/views/PoolContainer.vue, yarn.lock
[PW-638]: User can't see remove liquidity screen by direct link
=> Wait for liquidity subscriptions creation

src/components/Input/TokenAddress.vue, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hr.json, src/lang/hu.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/messages.ts, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/sk.json, src/lang/sr.json, src/lang/sv.json, src/lang/vi.json, src/lang/yo.json, src/lang/zh_CN.json, src/styles/_mixins.scss, src/views/Bridge.vue
[PW-649]: Add copy feature for bridge accounts.
* Bridge: Added Networks Copy Functionality.
[PW-649]: https://soramitsu.atlassian.net/browse/PW-649
=> PW-649: Add copy feature for bridge accounts

package.json, src/components/ConfirmSwap.vue, src/components/TransactionDetails/SwapTransactionDetails.vue, src/consts/index.ts, src/store/settings/getters.ts, src/store/swap/actions.ts, src/store/swap/getters.ts, src/store/swap/mutations.ts, src/store/swap/types.ts, src/views/Swap.vue, tests/mocks/components/SwapInfo.ts, yarn.lock
[Add select extension dialog](https://soramitsu.atlassian.net/browse/PW-668)
=> Select extension

src/views/ReferralProgram.vue
=> Release/fleek pre/1.8.1

env.json, public/env.json, src/store/consts.ts, src/store/settings/getters.ts, src/store/settings/types.ts, src/views/Swap.vue
[PW-685]: Charts: Add Setting to Show/Hide Charts
* Charts: Added Charts Enabled Settings.
[PW-685]: https://soramitsu.atlassian.net/browse/PW-685
=> PW-685: Charts: Add Setting to Show/Hide Charts

src/store/settings/actions.ts, src/types/nodes.ts, vue.config.js
https://soramitsu.atlassian.net/browse/PW-695
=> Loop through the node list

src/store/rewards/actions.ts, src/store/rewards/mutations.ts, src/store/rewards/state.ts, src/store/rewards/types.ts, src/views/Rewards.vue
[PW-707]: After rewards claiming user sees 0 PSWAP, 0 VAL placeholder
=> [PW-707] Fix rewards list after claim

src/modules/demeterFarming/mixins/PoolMixin.ts
[PW-706]: Demeter farming: Pool share after could be calculated as more than 100%
=> [PW-706] Fix pool share after calculation

src/components/App/Menu/AppInfoPopper.vue, src/components/HelpDialog.vue
[PW-705]: Info & community links texts are not translated after changing language
=> [PW-705] Fix Info & Community links text

src/consts/index.ts, src/modules/demeterFarming/components/PoolCard.vue
[PW-708]: Add link to Demeter farming platform
=> [PW-708] Add Demeter farming platform link

src/components/Charts.vue
[PW-689]: Charts: Add Chart for 2 Tokens
=> Add chart for 2 tokens

src/store/demeterFarming/getters.ts, src/store/removeLiquidity/actions.ts, src/store/removeLiquidity/getters.ts, src/views/RemoveLiquidity.vue
[PW-736]: Update Remove liquidity logic (with locked tokens)
=> Fix remove liquidity with locked tokens

src/modules/demeterFarming/components/StakeDialog.vue, src/styles/_mixins.scss, src/views/RemoveLiquidity.vue
[PW-759]: Add MAX button for Demeter staking
=> Add MAX buttons to farming and remove liquidity

Jenkinsfile
[DOPS-1835]: Polkaswap cd.
1. Add copy env.json.
Signed-off-by: Pavel Varfolomeev <wpi86@yandex.ru>
=> [DOPS-1835]: Polkaswap cd.

src/store/addLiquidity/actions.ts, src/views/AddLiquidity.vue
[PW-772]: Pools. Add liquidity button paste last asset
=> Clear addLiqudity selected tokens on destroyed

src/store/web3/state.ts, src/utils/ethers-util.ts, src/views/Bridge.vue
[PW-733]: Fix Bridge check for network type in metamask
=> Fix Bridge check for network type in metamask

src/components/App/Header/AppHeader.vue, src/components/PairTokenLogo.vue, src/components/Rewards/TokensRow.vue, src/components/mixins/BridgeHistoryMixin.ts, src/consts/index.ts, src/router/index.ts, src/store/bridge/getters.ts, src/store/bridge/mutations.ts, src/store/bridge/state.ts, src/store/bridge/types.ts, src/views/BridgeTransactionsHistory.vue, src/views/MoonpayHistory.vue, src/views/ReferralProgram.vue
* Refactored Consts Code Duplication.
=> Consts Code Duplication Refactoring

Jenkinsfile-UCAN
[DOPS-1942]: Publish UCAN token.
1. Added schedule.
Signed-off-by: Pavel Varfolomeev <wpi86@yandex.ru>
=> [DOPS-1942]: Publish UCAN token.

package.json, src/components/Swap/Chart.vue, src/views/Tokens.vue, yarn.lock
[PW-786]: Charts: sometimes change rate is 0 although price has changed
=> Fix chart price change

package.json, src/modules/demeterFarming/components/PoolCard.vue, src/modules/demeterFarming/components/StakeDialog.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-785
=> update wallet to 1.10.21 & update not translated strings

src/components/Swap/Chart.vue
https://soramitsu.atlassian.net/browse/PW-786
=> Chart: reset zoom end

src/components/Swap/Chart.vue
[PW-788]: Replace chart price updates polling to Subquery subscription
=> Replace chart price updates polling to Subquery subscription

env.json, src/components/App/Header/AppHeader.vue, src/components/PairTokenLogo.vue, src/components/mixins/BridgeHistoryMixin.ts, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hr.json, src/lang/hu.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/sk.json, src/lang/sr.json, src/lang/sv.json, src/lang/vi.json, src/lang/yo.json, src/lang/zh_CN.json, src/store/bridge/actions.ts, src/utils/bridge/index.ts, src/views/Bridge.vue, src/views/BridgeTransactionsHistory.vue
[PW-810]: Disable HASHI Bridge.
1. Disable HASHI Bridge because of ETH Merge.
[PW-810]: https://soramitsu.atlassian.net/browse/PW-810
=> Disable bridge

src/components/App/Header/AppHeader.vue, src/components/mixins/BridgeHistoryMixin.ts, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hr.json, src/lang/hu.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/sk.json, src/lang/sr.json, src/lang/sv.json, src/lang/vi.json, src/lang/yo.json, src/lang/zh_CN.json, src/store/bridge/actions.ts, src/utils/bridge/index.ts, src/views/Bridge.vue, src/views/BridgeTransactionsHistory.vue
[PW-813]: ETH migration.
1. ETH migration.
[PW-813]: https://soramitsu.atlassian.net/browse/PW-813
=> [PW-813]: ETH migration

package.json, src/components/Input/TokenInput.vue, src/components/Rewards/AmountHeader.vue, src/views/Wallet.vue, yarn.lock
1. Fix wallet paddings.
2. Fix zero fiat values when subquery is down
=> Fix 1.10 issues

src/components/SettingsDialog.vue, src/store/settings/getters.ts
[PW-871]: Hide Charts Switch Settings By Env Flag.
* Hide Charts Switch Settings By Env Flag.
[PW-871]: https://soramitsu.atlassian.net/browse/PW-871
=> PW-871: Hide Charts Switch Settings By Env Flag

src/components/Swap/Chart.vue
https://soramitsu.atlassian.net/browse/PW-869
=> Fix swap chart Y label

src/App.vue
=> Referral Page Tabs Fix

src/App.vue
[PW-874]: Rewards Tabs Underline Fix
* Fixed Rewards Tabs Underline.
[PW-874]: https://soramitsu.atlassian.net/browse/PW-874
=> PW-874: Rewards Tabs Underline Fix

package.json, public/env.json, src/App.vue, src/views/BridgeTransaction.vue, src/views/BridgeTransactionsHistory.vue, yarn.lock
1. Fix block explorer links.
2. Fix local env file.
3. Fix issue with infinite loader on Bridge history page (when subquery is down)
=> Fix issues

package.json
[DOPS-2049]: Image updater.
1. Need new image for test.
=> [DOPS-2049]: Image updater.

src/modules/demeterFarming/mixins/PoolMixin.ts, src/store/demeterFarming/getters.ts, src/store/removeLiquidity/getters.ts, src/utils/index.ts
[PW-929]: 100% of your pool is in staking with XOR does not allow to remove liquidity in pool with XSTUSD
=> Fix remove xstusd liquidity

package.json, src/store/settings/actions.ts, yarn.lock
https://soramitsu.atlassian.net/browse/PW-990
=> Improve connection process

package.json, src/components/Settings/Node/NodeInfo.vue, src/styles/_mixins.scss, src/views/Explore/Tokens.vue, src/views/Swap.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-986
https://soramitsu.atlassian.net/browse/PW-989
https://soramitsu.atlassian.net/browse/PW-811
https://soramitsu.atlassian.net/browse/PW-991
https://soramitsu.atlassian.net/browse/PW-913
=> Fix css for swap fiat values

src/styles/_mixins.scss, src/views/Explore/Demeter.vue, src/views/Explore/Pools.vue
https://soramitsu.atlassian.net/browse/PW-988
=> Explore page: rename investment column to balance

src/store/bridge/actions.ts, src/utils/bridge/history.ts, src/views/BridgeTransactionsHistory.vue
https://soramitsu.atlassian.net/browse/PW-998
=> Add restore history button to bridge history view

package.json, src/views/Explore/Demeter.vue, src/views/Explore/Pools.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-969
=> Update formattedAmount component & add prefix to explore pages balance

src/App.vue
[PW-936]: Fix referral system delay.
1. Fix referral system delay.
[PW-936]: https://soramitsu.atlassian.net/browse/PW-936
=> Fix referral system delay

src/components/SelectAsset/SelectToken.vue, src/views/Swap.vue
[PW-1000]: Fix custom token logic.
1. Fix custom token logic.
[PW-1000]: https://soramitsu.atlassian.net/browse/PW-1000
=> Fix custom token logic

Jenkinsfile
[DOPS-2188]: deploy trigger removal
1. deploy trigger removal
[DOPS-2188]: https://soramitsu.atlassian.net/browse/DOPS-2188
Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>
=> [DOPS-2188]: deploy trigger removal

src/views/Explore/Container.vue
https://soramitsu.atlassian.net/browse/PW-1080
=> Fix json error on explore page

Jenkinsfile
[DOPS-2232]: Generate k8s env for PR.
1. Add pr env generation.
Signed-off-by: Pavel Varfolomeev <wpi86@yandex.ru>
=> Test PR generation

src/components/SoraCard/steps/Email.vue, src/components/SoraCard/steps/Phone.vue, src/store/soraCard/getters.ts
[PW-1076](https://soramitsu.atlassian.net/browse/PW-1076?atlOrigin=eyJpIjoiNWFiZThiNzFjNDBmNDA2YjlkZTU2ZGMzMjQ1MDc3MjUiLCJwIjoiaiJ9)
=> Otp resend try fix

Jenkinsfile
[DOPS-2229] compaire polkaswap changes
1. Added new parameter from jenkins library
Signed-off-by: name <zaporozhets@soramitsu.co.jp>
[DOPS-2229]: https://soramitsu.atlassian.net/browse/DOPS-2229
=> [DOPS-2229] compaire polkaswap changes

Jenkinsfile
Duty/04-05-23: Fix Jenkinsfile PR-generator part
1. Fix Jenkinsfile PR-generator part.
=> Duty/04-05-23: Fix Jenkinsfile PR-generator part

src/views/BridgeTransaction.vue
https://exchange-1095.dev.sora2.tachi.soramitsu.co.jp/#/bridge/
=> Fix transaction view balance check

src/components/App/Footer/AppFooter.vue
[PW-1188]: Fix node name in status bar.
1. Fixed node name in status bar.
[PW-1188]: https://soramitsu.atlassian.net/browse/PW-1188
=> Fix node name in status bar

package.json, yarn.lock
https://github.com/sora-xor/sora2-network/pull/635
=> XST LP fee update

package.json, src/components/mixins/TranslationMixin.ts, src/components/pages/Bridge/SelectAccount.vue, src/components/pages/Bridge/TransactionDetails.vue, src/components/shared/Dialog/ConfirmBridgeTransaction.vue, src/consts/sub.ts, src/lang/en.json, src/lang/messages.ts, src/router/index.ts, src/store/bridge/actions.ts, src/store/bridge/getters.ts, src/store/web3/actions.ts, src/store/web3/getters.ts, src/store/web3/mutations.ts, src/store/web3/state.ts, src/store/web3/types.ts, src/utils/bridge/sub/classes/history.ts, src/utils/bridge/sub/classes/reducers.ts, src/utils/bridge/sub/utils.ts, src/views/Bridge.vue, src/views/BridgeContainer.vue, src/views/BridgeTransaction.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-1222
https://soramitsu.atlassian.net/browse/PW-1223
https://soramitsu.atlassian.net/browse/PW-1224
https://soramitsu.atlassian.net/browse/PW-1225
=> Fix sub bridge address issues

src/components/mixins/SelectAssetMixin.ts, src/components/pages/Bridge/SelectAsset.vue, src/components/shared/SelectAsset/SelectToken.vue
https://soramitsu.atlassian.net/browse/PW-1219
=> Fix assets sorting order in swap and bridge

Jenkinsfile
=> update node (master)

Jenkinsfile
=> Update node (develop)

src/indexer/queries/assetSupply.ts
[PW-1272]: Fix circulating supply for VAL & PSWAP on prod env.
1. Made calculations for the approximate estimation of the difference between circulating & total supply for VAL & PSWAP between mof node and blockchain queries
2. Added constants for the difference between circulating & total supply for VAL & PSWAP (mainnet only)
3. Fixed circulating supply for VAL & PSWAP on prod env
[PW-1272]: https://soramitsu.atlassian.net/browse/PW-1272
=> Fix circulating supply for VAL & PSWAP on prod env

src/components/mixins/TranslationMixin.ts, src/components/pages/Bridge/TransactionDetails.vue, src/consts/index.ts, src/views/BridgeTransaction.vue
https://soramitsu.atlassian.net/browse/PW-1285
=> [Bridge] Add max prefix to external network fee

src/components/mixins/BridgeMixin.ts, src/components/pages/Bridge/TransferNotification.vue, src/store/bridge/actions.ts, src/store/bridge/getters.ts, src/store/web3/actions.ts, src/utils/bridge/eth/classes/history.ts, src/utils/bridge/sub/classes/adapter.ts, src/utils/bridge/sub/classes/history.ts, src/utils/ethers-util.ts, src/views/Bridge.vue, src/views/BridgeTransaction.vue
1) Sub bridge history restoration improvements & optimization
2) FIx asset locked amount used for SORA Parachain
3) Do not reset WalletConnect session
=> Fix bridge issues

package.json, src/components/App/Alerts/AlertList.vue, src/components/App/Alerts/CreateAlert.vue, src/components/mixins/SelectedTokensRouteMixin.ts, src/components/pages/Moonpay/BridgeInitMixin.ts, src/components/pages/Moonpay/Confirmation.vue, src/components/pages/Stats/SupplyChart.vue, src/components/shared/SelectAsset/SelectToken.vue, src/components/shared/Skeleton/DataRow.vue, src/consts/index.ts, src/indexer/queries/assets.ts, src/store/assets/getters.ts, src/store/bridge/getters.ts, src/store/demeterFarming/actions.ts, src/utils/index.ts, src/views/Explore/Demeter.vue, src/views/Explore/Pools.vue, src/views/Explore/Tokens.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-771
https://soramitsu.atlassian.net/browse/PW-1324
=> Whitelist usage rationalization

src/components/pages/Swap/Chart.vue
https://soramitsu.atlassian.net/browse/PW-1279
=> fix prices precision on chart

src/components/mixins/ChartSpecMixin.ts, src/components/pages/Swap/Chart.vue
https://soramitsu.atlassian.net/browse/PW-939
=> Fix chart Y axis for assets with very low price

src/components/App/Alerts/CreateAlert.vue, src/components/mixins/ChartSpecMixin.ts, src/components/pages/Stats/SupplyChart.vue, src/components/pages/Swap/Chart.vue, src/components/pages/Swap/StatusActionBadge.vue, src/components/shared/Chart/ChartSkeleton.vue, src/components/shared/Input/TokenInput.vue, src/components/shared/Input/TokenSelectButton.vue, src/store/assets/mutations.ts, src/store/bridge/getters.ts, src/store/bridge/mutations.ts, src/store/web3/actions.ts, src/store/web3/mutations.ts, src/store/web3/types.ts, src/styles/_mixins.scss, src/views/Bridge.vue
https://soramitsu.atlassian.net/browse/PW-1344
=> Bridge sub account & token autoselects

src/components/App/Alerts/AlertList.vue, src/components/shared/PriceChange.vue, src/store/soraCard/actions.ts, src/utils/index.ts, src/views/Bridge.vue
https://soramitsu.atlassian.net/browse/PW-1345
=> Fix bridge max value precision

src/store/bridge/actions.ts, src/views/Bridge.vue
https://soramitsu.atlassian.net/browse/PW-1347
https://soramitsu.atlassian.net/browse/PW-1349
=> Fix bridge fees issues

package.json, src/components/mixins/BridgeMixin.ts, src/components/mixins/NetworkFormatterMixin.ts, src/components/pages/Bridge/SelectAccount.vue, src/components/pages/Bridge/SelectNetwork.vue, src/components/pages/Swap/Chart.vue, src/consts/sub.ts, src/store/assets/actions.ts, src/store/bridge/actions.ts, src/store/bridge/getters.ts, src/store/web3/actions.ts, src/store/web3/getters.ts, src/store/web3/types.ts, src/types/bridge.ts, src/utils/bridge/sub/classes/adapter.ts, src/utils/bridge/sub/classes/history.ts, src/utils/bridge/sub/classes/reducers.ts, src/utils/bridge/sub/utils.ts, src/views/Bridge.vue, src/views/BridgeTransaction.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-1220
https://soramitsu.atlassian.net/browse/PW-1277
https://soramitsu.atlassian.net/browse/PW-1278
https://soramitsu.atlassian.net/browse/PW-1284
https://soramitsu.atlassian.net/browse/PW-1325
https://soramitsu.atlassian.net/browse/PW-1349
https://soramitsu.atlassian.net/browse/PW-1359
=> Chart, Bridge, Wallet, ADAR fixes

src/components/mixins/ChartSpecMixin.ts, src/components/pages/Stats/BarChart.vue, src/components/pages/Stats/TvlChart.vue, src/components/pages/Swap/Chart.vue, src/indexer/queries/price/asset.ts, src/indexer/queries/price/orderBook.ts, src/types/chart.ts
https://soramitsu.atlassian.net/browse/PW-1057
=> [OrderBook] add volume chart

src/components/pages/Swap/Chart.vue
https://soramitsu.atlassian.net/browse/PW-1385
=> Fix chart current price

src/consts/index.ts
[PW-1399]: Add staking routing in menu.
1. Add staking routing in menu.
[PW-1399]: https://soramitsu.atlassian.net/browse/PW-1399
=> Add staking routing in menu

src/store/web3/actions.ts
https://soramitsu.atlassian.net/browse/PW-1431
=> Fix ss58 check

package.json, src/consts/sub.ts
https://soramitsu.atlassian.net/browse/PW-1433
=> set kusama incoming xcm fee 0.01KSM

package.json, src/store/web3/getters.ts
Related to https://github.com/paritytech/polkadot-sdk/issues/3345
=> Release 1.29.1

package.json, public/env.json, src/indexer/queries/kensetsu.ts, src/indexer/queries/pools.ts, src/indexer/queries/referrals.ts, src/store/pool/actions.ts, src/store/referrals/actions.ts, src/store/referrals/mutations.ts, src/store/referrals/state.ts, src/store/referrals/types.ts, src/views/ReferralProgram.vue, yarn.lock
https://soramitsu.atlassian.net/browse/PW-1507
=> [Tech] queries from wallet

src/store/bridge/actions.ts, src/utils/bridge/eth/utils.ts
https://soramitsu.atlassian.net/browse/PW-1610
1. Fixed "Metamask - RPC error:  ETH value should be more than 0"
=> improve eth fee calculation

src/utils/bridge/sub/classes/reducers.ts
https://soramitsu.atlassian.net/browse/PW-1620
=> Fix bridge sora link

src/utils/regexp.ts, src/views/ReferralProgram.vue
[PW-1206]: User can be his own referral if he pastes address in Polkadot format
1. Checked if is sora address format
[PW-1206]: https://soramitsu.atlassian.net/browse/PW-1206
=> check_refer_address_sora

src/components/shared/Widget/PriceChart.vue
* updated_with_using_cash_chart
* deleted_useless_things_and_console_info
* deleted_unnecessary_reverse_chart_false
* price_chart_updated
* deleted_useless_console_infos
* fixed_straight_price_when_revert
* deleted_useless_line
* empty_lines_deleted
* updated_some_logic
* updated_reverse_chart
* updated_code_for_recude_complexity
* updated_according_to_comments
* update fillSnapshotBuffer
* update fetchData
---------
=> Fix/chart revert button causes data reload (#1464)

src/views/Explore/Tokens.vue
[PW-1598]: Some synthetic assets look badly in the tokens list.
[PW-1598]: https://soramitsu.atlassian.net/browse/PW-1598
=> change_width_for_token_column

src/components/pages/OrderBook/TransactionDetails.vue, src/utils/ethers-util.ts
https://soramitsu.atlassian.net/browse/PW-1713
=> [Bridge] Update methods to connect/disconnect ethereum wallet

src/components/mixins/Widget/WithTokenSelect.ts, src/components/shared/SelectAsset/SelectToken.vue, src/components/shared/Stats/StatsFilter.vue, src/components/shared/Widget/Base.vue, src/components/shared/Widget/PriceChart.vue, src/components/shared/Widget/SupplyChart.vue, src/components/shared/Widget/TokenPriceChart.vue, src/consts/index.ts, src/views/Swap.vue
https://soramitsu.atlassian.net/browse/PW-1721
=> Use TokenPriceChartWidget in swap page

env.json, package.json, yarn.lock
=> [Tech] update wallet & enable alt prod env

src/components/App/Header/AppHeaderMenu.vue, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/hr.json, src/lang/hu.json, src/lang/hy.json, src/lang/id.json, src/lang/it.json, src/lang/nl.json, src/lang/no.json, src/lang/pl.json, src/lang/ru.json, src/lang/sk.json, src/lang/sr.json, src/lang/sv.json, src/lang/vi.json, src/lang/yo.json, src/lang/zh_CN.json
=> fixed_bugs_and_languages_in_side_menu

package.json, yarn.lock
=> update wallet to 1.41.1

src/utils/bridge/common/utils.ts, src/utils/bridge/eth/classes/history.ts, src/views/BridgeTransaction.vue
=> [Bridge] Add ability to retry failed but mined Ethereum transaction

src/components/pages/Bridge/AccountPanel.vue
- _Improved styles for bridge connected wallet icon_
- _Rounded logos look better_
---
---
- _All wallets should be connected and checked how does the icon look per each wallet_
---
Before:
After:
---
=> Fix bridge connected wallet icon

src/lang/index.ts, yarn.lock
=> fix dayjs en locale

src/router/index.ts
=> commented_route

src/App.vue, src/consts/index.ts, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/id.json, src/lang/it.json, src/lang/nl.json, src/lang/pl.json, src/lang/ru.json, src/lang/sr.json, src/lang/vi.json, src/lang/zh_CN.json, src/router/index.ts, src/views/PointSystemWrapper.vue, src/views/RewardsTabs.vue
- Change router for Point System
- Before we have 2 routes for 2 different versions of Point System, now we have only 1 route
---
---
---
---
---
---
=> fixed_route_with_wrapper

package.json, src/App.vue, src/views/PointSystemV2.vue, vite.config.ts, yarn.lock
=> Change vite vue plugin & fix App load

package.json, vite.config.ts, yarn.lock
=> Add node polyfills

src/utils/ethers-util.ts
- Fix Metamask permissiions parsing
- Users have issues connecting MetaMask on 12.6.0
---
---
---
---
---
---
=> Fix wallet permissions parsing

src/App.vue, src/views/Wallet.vue
- _I've added a support for send routing_
- _So it's possible to integrate direct links to the wallet send feature for different purposes_
---
---
- _[User story](https://soramitsu.atlassian.net/browse/PW-1804)_ 
---
- _Format of link: http://localhost:8080/#/wallet?page=send&asset=kusd&to=cnWbtu2u7c51SPpYFr3SYDwTZkq1vF2bbaqAkCZvtCxsE19i3&amount=1000_
- _A link should have query param `page=send`_
- _]asset] parameter is also required for WalletSend component. It should be set by asset symbol from the whitelisted tokens_
- _`to` and `amount` params are optional_
- _If account isn’t connected then it’s not possible to navigate to the WalletSend flow_
---
- _Link to env: …
=> Add send routing

package.json, src/components/pages/OrderBook/Popovers/PairListPopover.vue, src/lang/cs.json, src/lang/de.json, src/lang/en.json, src/lang/es.json, src/lang/fr.json, src/lang/id.json, src/lang/it.json, src/lang/messages.ts, src/lang/nl.json, src/lang/pl.json, src/lang/ru.json, src/lang/sr.json, src/lang/vi.json, src/lang/zh_CN.json, src/views/OrderBook.vue, src/views/ReferralBonding.vue, src/views/RewardsTabs.vue, src/views/Wallet.vue
- _I've fixed amount as query parameter for Wallet Send routing_
- _Improved styles for rewards tabs_
- _Improved orderbook sorting by default_
- _And fixed translations for Referral Program_
- _So it doesn't have any issues in WalletSend component, styles were improved and translations became better_
---
---
- _[Parse numbers in query issue](https://soramitsu.atlassian.net/browse/PW-1804?focusedCommentId=49113)_ 
- _[Wrong translations for Referral Program](https://soramitsu.atlassian.net/browse/PW-1805)_
- _[Rewards styles issue](https://soramitsu.atlassian.net/browse/PW-1807)_
- _[Improve orderbook sorting by default](https://soramitsu.atlassian.net/browse/PW-1808)_
---
- _Type to input …
=> Fix amount as query param for Wallet Transfer

src/components/mixins/IndexerDataFetchMixin.ts, src/components/pages/Swap/Widget/Transactions.vue, src/modules/vault/components/VaultDetailsHistory.vue
- Added `fetchAmount `property (for indexer request)
- Added usd amounts for input & output columns
- Added token selector
- An attempt to make the widget more user-friendly.
---
---
- [Improve swap transactions widget](https://soramitsu.atlassian.net/browse/PW-1809)
---
---
- 
---
---
=> Improve transactions widget
